// cli/templates/frontend/vite-vue-ts/src/App.vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue'
import { invoke } from 'versapy/api'

async function greet() {
  console.log(
    await invoke("greet", {name: "World !"})
  )
}

</script>

<template>
  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Versapy + Vite + Vue" />
  <button @click="greet">
    Greetings from Versapy
  </button>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// cli/templates/frontend/vite-react-ts/src/App.tsx
import { invoke } from "versapy/api"
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

function App() {
  
  const greet = async () => {

    console.log(
      await invoke("greet", {name: "World !"})
    )

  }

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Versapy + Vite + React</h1>
      <button onClick={() => greet()}>
          Greetings from Versapy
        </button>
    </>
  )
}

export default App
