// cli/templates/frontend/vite-react-ts/src/App.tsx
import { invoke } from "versapy/api"
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

function App() {
  
  const greet = async () => {

    console.log(
      await invoke("greet", {name: "World !"})
    )

  }

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Versapy + Vite + React</h1>
      <button onClick={() => greet()}>
          Greetings from Versapy
        </button>
    </>
  )
}

export default App

// cli/templates/frontend/vite-qwik/src/app.jsx
import { component$ } from '@builder.io/qwik'
import qwikLogo from './assets/qwik.svg'
import viteLogo from '/vite.svg'

import { invoke } from "versapy/api"

import './app.css'

export const App = component$(() => {

  const greet = async () => {

    console.log(
      await invoke("greet", {name: "World !"})
    )

  }

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} class="logo" alt="Vite logo" />
        </a>
        <a href="https://qwik.dev" target="_blank">
          <img src={qwikLogo} class="logo qwik" alt="Qwik logo" />
        </a>
      </div>
      <h1>Versapy + Vite + Qwik</h1>
      
      <button onClick$={() => greet()}>
        Greetings from Versapy
      </button>
    
    </>
  )
})
